<?php $editing = is_array($post); $action = $editing ? '/admin/blog/' . (int) $post['id'] : '/admin/blog'; ?>
<header class="dashboard-page-header"><div><p class="dashboard-kicker"><i class="ph ph-pencil-line" aria-hidden="true"></i><span>Plain-text publishing</span></p><h1><?= $editing ? 'Edit Blog post' : 'Create Blog post' ?></h1><p>Use plain text. Publication remains a separate explicit action.</p></div><a class="button button--quiet" href="/admin/blog"><i class="ph ph-arrow-left" aria-hidden="true"></i><span>Blog list</span></a></header>
<form class="dashboard-panel form-stack mt-8" action="<?= e($action) ?>" method="post" enctype="multipart/form-data" data-form-kind="entry"><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><?php if ($editing): ?><input type="hidden" name="updated_at" value="<?= e($post['updated_at']) ?>"><?php endif; ?>
<?php $fieldTargets = ['cover_image' => 'cover_image']; $fieldLabels = ['title' => 'Title', 'slug' => 'Slug', 'category' => 'Category', 'meta_title' => 'Meta title', 'meta_description' => 'Meta description', 'excerpt' => 'Excerpt', 'body' => 'Body', 'cover_image' => 'Cover image']; $formErrorSummaryId = 'blog-editor-error-summary'; require base_path('app/Views/components/form-errors.php'); ?>
<p class="form-required-note"><i class="ph ph-asterisk" aria-hidden="true"></i><span>Title, excerpt, and body are required.</span></p>
<?php foreach ([['title','Title','text',3,180,'A clear public headline.'],['slug','Slug','text',0,200,'Lowercase URL slug; leave blank on create to derive it from the title.'],['category','Category','text',0,100,'A short public label such as Community or Guides.'],['meta_title','Meta title','text',0,190,'Optional search and social title.'],['meta_description','Meta description','text',0,300,'Optional bounded search and social summary.']] as [$name,$label,$type,$min,$max,$help]): $error=field_error($errors,$name); $required=$name==='title'; ?><div class="field-group"><label for="<?= e($name) ?>"><?= e($label) ?><?= $required ? '' : ' <span class="field-label-note">Optional</span>' ?></label><input id="<?= e($name) ?>" name="<?= e($name) ?>" type="<?= e($type) ?>"<?= $min > 0 ? ' minlength="' . e($min) . '"' : '' ?> maxlength="<?= e($max) ?>"<?= $name === 'slug' ? ' pattern="[a-z0-9]+(?:-[a-z0-9]+)*"' : '' ?> value="<?= e($old[$name] ?? ($post[$name] ?? '')) ?>" data-form-label="<?= e($label) ?>" aria-describedby="<?= e($name) ?>-help<?= $error ? ' ' . e($name) . '-error' : '' ?>"<?= $required ? ' required' : '' ?><?= $error ? ' aria-invalid="true"' : '' ?>><p id="<?= e($name) ?>-help" class="field-help"><?= e($help) ?></p><?php if ($error): ?><p id="<?= e($name) ?>-error" class="field-error" role="alert"><?= e($error) ?></p><?php endif; ?></div><?php endforeach; ?>
<?php foreach ([['excerpt','Excerpt',20,500,4,'Summarize the story for Blog cards.'],['body','Body',40,50000,14,'Separate paragraphs with a blank line. HTML is not accepted.']] as [$name,$label,$min,$max,$rows,$help]): $error=field_error($errors,$name); ?><div class="field-group"><label for="<?= e($name) ?>"><?= e($label) ?></label><textarea id="<?= e($name) ?>" name="<?= e($name) ?>" minlength="<?= e($min) ?>" maxlength="<?= e($max) ?>" rows="<?= e($rows) ?>" data-form-label="<?= e($label) ?>" aria-describedby="<?= e($name) ?>-help<?= $error ? ' ' . e($name) . '-error' : '' ?>" required<?= $error ? ' aria-invalid="true"' : '' ?>><?= e($old[$name] ?? ($post[$name] ?? '')) ?></textarea><p id="<?= e($name) ?>-help" class="field-help"><?= e($help) ?></p><?php if ($error): ?><p id="<?= e($name) ?>-error" class="field-error" role="alert"><?= e($error) ?></p><?php endif; ?></div><?php endforeach; ?>
<div class="field-group"><label for="cover_image">Cover image <span class="field-label-note">Optional</span></label><input id="cover_image" name="cover_image" type="file" accept="image/jpeg,image/png,image/webp" data-form-label="Cover image" data-max-bytes="5242880" aria-describedby="cover-image-help<?= field_error($errors,'cover_image') ? ' cover-image-error' : '' ?>"><p id="cover-image-help" class="field-help">Optional JPEG, PNG, or WebP. Maximum 5 MB and 16 million decoded pixels.</p><?php if ($error=field_error($errors,'cover_image')): ?><p id="cover-image-error" class="field-error" role="alert"><?= e($error) ?></p><?php endif; ?><?php if ($editing && !empty($post['cover_image'])): ?><img class="mt-3 aspect-[16/9] w-full max-w-sm rounded-xl object-cover" src="<?= e($post['cover_image']) ?>" alt="Current cover image" width="640" height="360"><?php endif; ?></div>
<button class="button button--primary w-full sm:w-auto" type="submit" data-submit-label="<?= $editing ? 'Saving post…' : 'Creating draft…' ?>"><i class="ph ph-floppy-disk" aria-hidden="true"></i><span data-submit-text><?= $editing ? 'Save changes' : 'Create draft' ?></span></button></form>
