<header class="dashboard-page-header"><div><p class="dashboard-kicker"><i class="ph ph-newspaper" aria-hidden="true"></i><span>Editorial publishing</span></p><h1>Blog</h1><p>Create plain-text guides and publish them to public discovery.</p></div><a class="button button--primary" href="/admin/blog/create"><i class="ph ph-plus" aria-hidden="true"></i><span>New post</span></a></header>

<form class="dashboard-panel mt-8 grid gap-4 sm:grid-cols-[1fr_auto_auto] sm:items-end" action="/admin/blog" method="get">
    <div class="field-group"><label for="blog-search">Search</label><input id="blog-search" name="search" type="search" maxlength="100" value="<?= e($filters['search'] ?? '') ?>"></div>
    <div class="field-group"><label for="blog-status">Status</label><select id="blog-status" name="status"><option value="">All</option><option value="draft"<?= ($filters['status'] ?? '') === 'draft' ? ' selected' : '' ?>>Draft</option><option value="published"<?= ($filters['status'] ?? '') === 'published' ? ' selected' : '' ?>>Published</option></select></div>
    <button class="button button--quiet" type="submit">Apply filters</button>
</form>

<?php if ($posts === []): ?><section class="dashboard-panel mt-6 text-center"><i class="ph ph-notebook text-3xl" aria-hidden="true"></i><h2 class="mt-3 text-xl font-bold">No Blog posts found</h2><p class="mt-2 text-sm text-[var(--ink-muted)]">Create a draft or clear the current filters.</p></section><?php else: ?>
<div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Managed Blog posts</caption><thead><tr><th>Post</th><th>Status</th><th>Updated</th><th>Actions</th></tr></thead><tbody><?php foreach ($posts as $post): ?><tr><td data-label="Post"><strong><?= e($post['title']) ?></strong><small>/blog/<?= e($post['slug']) ?></small></td><td data-label="Status"><span class="status-chip status-chip--<?= e($post['status']) ?>"><?= e(ucfirst($post['status'])) ?></span></td><td data-label="Updated"><?= e($post['updated_at']) ?></td><td class="organizer-table__action" data-label="Actions"><div class="admin-table-actions"><a class="button button--quiet button--compact" href="/admin/blog/<?= e($post['id']) ?>/edit">Edit</a><a class="button button--quiet button--compact" href="/admin/blog/<?= e($post['id']) ?>/preview">Preview</a><form action="/admin/blog/<?= e($post['id']) ?>/<?= $post['status'] === 'published' ? 'unpublish' : 'publish' ?>" method="post"><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="updated_at" value="<?= e($post['updated_at']) ?>"><button class="button button--primary button--compact" type="submit"><?= $post['status'] === 'published' ? 'Unpublish' : 'Publish' ?></button></form><form action="/admin/blog/<?= e($post['id']) ?>/delete" method="post"><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="updated_at" value="<?= e($post['updated_at']) ?>"><button class="button button--danger button--compact" type="submit">Delete</button></form></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php $pageHref = static fn (int $page): string => '/admin/blog?' . http_build_query(array_filter(['status' => $filters['status'] ?? null, 'search' => $filters['search'] ?? null, 'page' => $page], static fn (mixed $value): bool => $value !== null && $value !== '')); ?>
<?php if (($pagination['last_page'] ?? 1) > 1): ?><nav class="mt-6 flex items-center justify-center gap-3" aria-label="Blog administration pagination"><?php if ($pagination['page'] > 1): ?><a class="button button--quiet" href="<?= e($pageHref($pagination['page'] - 1)) ?>">Previous</a><?php endif; ?><span class="text-sm text-[var(--ink-muted)]">Page <?= e($pagination['page']) ?> of <?= e($pagination['last_page']) ?></span><?php if ($pagination['page'] < $pagination['last_page']): ?><a class="button button--quiet" href="<?= e($pageHref($pagination['page'] + 1)) ?>">Next</a><?php endif; ?></nav><?php endif; ?>
<?php endif; ?>
