<?php

declare(strict_types=1);

use OEMS\App\Controllers\AuthController;
use OEMS\App\Controllers\AdminCategoryController;
use OEMS\App\Controllers\AdminAnalyticsController;
use OEMS\App\Controllers\AdminEventController;
use OEMS\App\Controllers\AdminReviewController;
use OEMS\App\Controllers\AdminPaymentController;
use OEMS\App\Controllers\AdminOrganizerController;
use OEMS\App\Controllers\AdminUserController;
use OEMS\App\Controllers\AdminReportController;
use OEMS\App\Controllers\AdminCmsController;
use OEMS\App\Controllers\AdminContactController;
use OEMS\App\Controllers\AdminNewsletterController;
use OEMS\App\Controllers\AdminSettingsController;
use OEMS\App\Controllers\AdminOperationsController;
use OEMS\App\Controllers\AdminBlogController;
use OEMS\App\Controllers\DashboardController;
use OEMS\App\Controllers\EventCalendarController;
use OEMS\App\Controllers\ApiEventController;
use OEMS\App\Controllers\HomeController;
use OEMS\App\Controllers\OrganizerAnnouncementController;
use OEMS\App\Controllers\OrganizerAnalyticsController;
use OEMS\App\Controllers\OrganizerEventController;
use OEMS\App\Controllers\OrganizerParticipantController;
use OEMS\App\Controllers\OrganizerCheckInController;
use OEMS\App\Controllers\OrganizerCouponController;
use OEMS\App\Controllers\OrganizerVenueController;
use OEMS\App\Controllers\OrganizerReviewController;
use OEMS\App\Controllers\ParticipantRegistrationController;
use OEMS\App\Controllers\ParticipantFavoriteController;
use OEMS\App\Controllers\ParticipantWaitlistController;
use OEMS\App\Controllers\ParticipantNotificationController;
use OEMS\App\Controllers\ParticipantTicketController;
use OEMS\App\Controllers\ParticipantCertificateController;
use OEMS\App\Controllers\ParticipantReviewController;
use OEMS\App\Controllers\ProfileController;
use OEMS\App\Controllers\PublicEventController;
use OEMS\App\Controllers\PublicCalendarController;
use OEMS\App\Controllers\PublicLocationController;
use OEMS\App\Controllers\PublicContentController;
use OEMS\App\Controllers\PublicContactController;
use OEMS\App\Controllers\PublicNewsletterController;
use OEMS\App\Controllers\PublicCertificateController;
use OEMS\App\Controllers\PublicBlogController;
use OEMS\App\Controllers\HealthController;
use OEMS\Core\Router;

return static function (Router $router): void {
    $router->get('/health/live', [HealthController::class, 'live'], name: 'health.live');
    $router->get('/health/ready', [HealthController::class, 'ready'], name: 'health.ready');
    $router->get('/', [HomeController::class, 'index'], name: 'home');
    $router->get('/events', [PublicEventController::class, 'index'], name: 'events.index');
    $router->get('/events/calendar', [PublicCalendarController::class, 'index'], name: 'events.calendar.index');
    $router->post('/events/location', [PublicLocationController::class, 'store'], ['csrf'], 'events.location.store');
    $router->post('/events/location/clear', [PublicLocationController::class, 'clear'], ['csrf'], 'events.location.clear');
    $router->get('/events/{slug}/calendar.ics', [EventCalendarController::class, 'publicIcs'], name: 'events.calendar');
    $router->get('/events/{slug}/google-calendar', [EventCalendarController::class, 'publicGoogle'], name: 'events.google-calendar');
    $router->get('/events/{slug}', [PublicEventController::class, 'show'], name: 'events.show');
    $router->get('/api/v1/events', [ApiEventController::class, 'index'], name: 'api.v1.events.index');
    $router->get('/api/v1/events/calendar', [ApiEventController::class, 'calendar'], name: 'api.v1.events.calendar');
    $router->get('/api/v1/events/{slug}', [ApiEventController::class, 'show'], name: 'api.v1.events.show');
    $router->get('/about', [PublicContentController::class, 'about'], name: 'pages.about');
    $router->get('/contact', [PublicContactController::class, 'index'], name: 'pages.contact');
    $router->post('/contact/submit', [PublicContactController::class, 'store'], ['csrf'], 'contact.store');
    $router->post('/newsletter/subscribe', [PublicNewsletterController::class, 'subscribe'], ['csrf'], 'newsletter.subscribe');
    $router->get('/newsletter/confirm/{token}', [PublicNewsletterController::class, 'confirm'], name: 'newsletter.confirm');
    $router->get('/newsletter/unsubscribe/{token}', [PublicNewsletterController::class, 'unsubscribe'], name: 'newsletter.unsubscribe');
    $router->get('/privacy', [PublicContentController::class, 'privacy'], name: 'pages.privacy');
    $router->get('/terms', [PublicContentController::class, 'terms'], name: 'pages.terms');
    $router->get('/faq', [PublicContentController::class, 'faq'], name: 'pages.faq');
    $router->get('/certificates/verify/{token}', [PublicCertificateController::class, 'show'], name: 'certificates.verify');
    $router->get('/blog', [PublicBlogController::class, 'index'], name: 'blog.index');
    $router->get('/blog/{slug}', [PublicBlogController::class, 'show'], name: 'blog.show');

    $router->get('/login', [AuthController::class, 'showLogin'], ['guest'], 'login');
    $router->post('/login', [AuthController::class, 'login'], ['guest', 'csrf'], 'login.submit');
    $router->get('/register', [AuthController::class, 'showRegister'], ['guest'], 'register');
    $router->post('/register', [AuthController::class, 'register'], ['guest', 'csrf'], 'register.submit');
    $router->get('/verify-email/resend', [AuthController::class, 'showResendVerification'], name: 'verification.notice');
    $router->post('/verify-email/resend', [AuthController::class, 'resendVerification'], ['csrf'], 'verification.resend');
    $router->get('/verify-email/{token}', [AuthController::class, 'verifyEmail'], name: 'verify-email');
    $router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], ['guest'], 'password.request');
    $router->post('/forgot-password', [AuthController::class, 'sendResetLink'], ['guest', 'csrf'], 'password.email');
    $router->get('/reset-password/{token}', [AuthController::class, 'showResetPassword'], ['guest'], 'password.reset');
    $router->post('/reset-password/{token}', [AuthController::class, 'resetPassword'], ['guest', 'csrf'], 'password.update');

    $router->post('/logout', [AuthController::class, 'logout'], ['auth', 'csrf'], 'logout');
    $router->get('/dashboard', [DashboardController::class, 'index'], ['auth'], 'dashboard');
    $router->get('/profile', [ProfileController::class, 'edit'], ['auth'], 'profile.edit');
    $router->post('/profile', [ProfileController::class, 'update'], ['auth', 'csrf'], 'profile.update');
    $router->get('/participant/dashboard', [DashboardController::class, 'participant'], ['role:participant'], 'participant.dashboard');
    $router->get('/participant/favorites', [ParticipantFavoriteController::class, 'index'], ['role:participant'], 'participant.favorites.index');
    $router->post('/participant/favorites/{id}', [ParticipantFavoriteController::class, 'store'], ['role:participant', 'csrf'], 'participant.favorites.store');
    $router->post('/participant/favorites/{id}/remove', [ParticipantFavoriteController::class, 'destroy'], ['role:participant', 'csrf'], 'participant.favorites.destroy');
    $router->get('/participant/waitlist', [ParticipantWaitlistController::class, 'index'], ['role:participant'], 'participant.waitlist.index');
    $router->post('/participant/events/{id}/waitlist', [ParticipantWaitlistController::class, 'store'], ['role:participant', 'csrf'], 'participant.waitlist.store');
    $router->post('/participant/waitlist/{id}/leave', [ParticipantWaitlistController::class, 'destroy'], ['role:participant', 'csrf'], 'participant.waitlist.destroy');
    $router->get('/participant/notifications', [ParticipantNotificationController::class, 'index'], ['role:participant'], 'participant.notifications.index');
    $router->post('/participant/notifications/read-all', [ParticipantNotificationController::class, 'markAllRead'], ['role:participant', 'csrf'], 'participant.notifications.read-all');
    $router->post('/participant/notifications/{id}/read', [ParticipantNotificationController::class, 'markRead'], ['role:participant', 'csrf'], 'participant.notifications.read');
    $router->get('/participant/events/{slug}/register', [ParticipantRegistrationController::class, 'create'], ['role:participant'], 'participant.registrations.create');
    $router->post('/participant/events/{slug}/register', [ParticipantRegistrationController::class, 'store'], ['role:participant', 'csrf'], 'participant.registrations.store');
    $router->get('/participant/registrations', [ParticipantRegistrationController::class, 'index'], ['role:participant'], 'participant.registrations.index');
    $router->get('/participant/registrations/{id}', [ParticipantRegistrationController::class, 'show'], ['role:participant'], 'participant.registrations.show');
    $router->get('/participant/registrations/{id}/calendar.ics', [EventCalendarController::class, 'registrationIcs'], ['role:participant'], 'participant.registrations.calendar');
    $router->get('/participant/registrations/{id}/google-calendar', [EventCalendarController::class, 'registrationGoogle'], ['role:participant'], 'participant.registrations.google-calendar');
    $router->post('/participant/registrations/{id}/cancel', [ParticipantRegistrationController::class, 'cancel'], ['role:participant', 'csrf'], 'participant.registrations.cancel');
    $router->post('/participant/registrations/{id}/payment', [ParticipantRegistrationController::class, 'submitPromotedPayment'], ['role:participant', 'csrf'], 'participant.registrations.payment');
    $router->get('/participant/tickets', [ParticipantTicketController::class, 'index'], ['role:participant'], 'participant.tickets.index');
    $router->get('/participant/tickets/{id}', [ParticipantTicketController::class, 'show'], ['role:participant'], 'participant.tickets.show');
    $router->get('/participant/tickets/{id}/qr', [ParticipantTicketController::class, 'qr'], ['role:participant'], 'participant.tickets.qr');
    $router->get('/participant/tickets/{id}/pdf', [ParticipantTicketController::class, 'pdf'], ['role:participant'], 'participant.tickets.pdf');
    $router->get('/participant/certificates', [ParticipantCertificateController::class, 'index'], ['role:participant'], 'participant.certificates.index');
    $router->post('/participant/registrations/{id}/certificate', [ParticipantCertificateController::class, 'issue'], ['role:participant', 'csrf'], 'participant.certificates.issue');
    $router->get('/participant/certificates/{id}/pdf', [ParticipantCertificateController::class, 'pdf'], ['role:participant'], 'participant.certificates.pdf');
    $router->get('/participant/reviews', [ParticipantReviewController::class, 'index'], ['role:participant'], 'participant.reviews.index');
    $router->get('/participant/events/{id}/review', [ParticipantReviewController::class, 'create'], ['role:participant'], 'participant.reviews.create');
    $router->post('/participant/events/{id}/review', [ParticipantReviewController::class, 'store'], ['role:participant', 'csrf'], 'participant.reviews.store');
    $router->get('/organizer/dashboard', [DashboardController::class, 'organizer'], ['role:organizer'], 'organizer.dashboard');
    $router->get('/organizer/check-in', [OrganizerCheckInController::class, 'verify'], ['role:organizer'], 'organizer.check-in.verify');
    $router->get('/organizer/analytics', [OrganizerAnalyticsController::class, 'index'], ['role:organizer'], 'organizer.analytics.index');
    $router->get('/organizer/analytics.csv', [OrganizerAnalyticsController::class, 'export'], ['role:organizer'], 'organizer.analytics.export');
    $router->get('/organizer/analytics.pdf', [OrganizerAnalyticsController::class, 'pdf'], ['role:organizer'], 'organizer.analytics.pdf');
    $router->get('/organizer/analytics.xml', [OrganizerAnalyticsController::class, 'spreadsheet'], ['role:organizer'], 'organizer.analytics.spreadsheet');
    $router->get('/organizer/coupons', [OrganizerCouponController::class, 'index'], ['role:organizer'], 'organizer.coupons.index');
    $router->get('/organizer/coupons/create', [OrganizerCouponController::class, 'create'], ['role:organizer'], 'organizer.coupons.create');
    $router->post('/organizer/coupons', [OrganizerCouponController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.coupons.store');
    $router->get('/organizer/coupons/{id}/edit', [OrganizerCouponController::class, 'edit'], ['role:organizer'], 'organizer.coupons.edit');
    $router->post('/organizer/coupons/{id}', [OrganizerCouponController::class, 'update'], ['role:organizer', 'csrf'], 'organizer.coupons.update');
    $router->post('/organizer/coupons/{id}/status', [OrganizerCouponController::class, 'status'], ['role:organizer', 'csrf'], 'organizer.coupons.status');
    $router->get('/organizer/events', [OrganizerEventController::class, 'index'], ['role:organizer'], 'organizer.events.index');
    $router->get('/organizer/events/create', [OrganizerEventController::class, 'create'], ['role:organizer'], 'organizer.events.create');
    $router->get('/organizer/events/trash', [OrganizerEventController::class, 'trash'], ['role:organizer'], 'organizer.events.trash');
    $router->post('/organizer/events/trash/{id}/restore', [OrganizerEventController::class, 'restore'], ['role:organizer', 'csrf'], 'organizer.events.restore');
    $router->post('/organizer/events', [OrganizerEventController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.events.store');
    $router->get('/organizer/events/{id}', [OrganizerEventController::class, 'show'], ['role:organizer'], 'organizer.events.show');
    $router->get('/organizer/events/{id}/edit', [OrganizerEventController::class, 'edit'], ['role:organizer'], 'organizer.events.edit');
    $router->post('/organizer/events/{id}', [OrganizerEventController::class, 'update'], ['role:organizer', 'csrf'], 'organizer.events.update');
    $router->post('/organizer/events/{id}/submit', [OrganizerEventController::class, 'submit'], ['role:organizer', 'csrf'], 'organizer.events.submit');
    $router->post('/organizer/events/{id}/publish', [OrganizerEventController::class, 'publish'], ['role:organizer', 'csrf'], 'organizer.events.publish');
    $router->post('/organizer/events/{id}/cancel', [OrganizerEventController::class, 'cancel'], ['role:organizer', 'csrf'], 'organizer.events.cancel');
    $router->post('/organizer/events/{id}/delete', [OrganizerEventController::class, 'delete'], ['role:organizer', 'csrf'], 'organizer.events.delete');
    $router->get('/organizer/events/{id}/announcements', [OrganizerAnnouncementController::class, 'index'], ['role:organizer'], 'organizer.announcements.index');
    $router->get('/organizer/events/{id}/announcements/create', [OrganizerAnnouncementController::class, 'create'], ['role:organizer'], 'organizer.announcements.create');
    $router->post('/organizer/events/{id}/announcements', [OrganizerAnnouncementController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.announcements.store');
    $router->get('/organizer/events/{id}/participants', [OrganizerParticipantController::class, 'index'], ['role:organizer'], 'organizer.participants.index');
    $router->get('/organizer/events/{id}/participants.csv', [OrganizerParticipantController::class, 'export'], ['role:organizer'], 'organizer.participants.export');
    $router->get('/organizer/events/{id}/check-in', [OrganizerCheckInController::class, 'index'], ['role:organizer'], 'organizer.check-in.index');
    $router->post('/organizer/events/{id}/check-in', [OrganizerCheckInController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.check-in.store');
    $router->get('/organizer/venues', [OrganizerVenueController::class, 'index'], ['role:organizer'], 'organizer.venues.index');
    $router->get('/organizer/venues/create', [OrganizerVenueController::class, 'create'], ['role:organizer'], 'organizer.venues.create');
    $router->post('/organizer/venues/geocode', [OrganizerVenueController::class, 'geocode'], ['role:organizer', 'csrf'], 'organizer.venues.geocode');
    $router->post('/organizer/venues', [OrganizerVenueController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.venues.store');
    $router->get('/organizer/venues/{id}/edit', [OrganizerVenueController::class, 'edit'], ['role:organizer'], 'organizer.venues.edit');
    $router->post('/organizer/venues/{id}', [OrganizerVenueController::class, 'update'], ['role:organizer', 'csrf'], 'organizer.venues.update');
    $router->post('/organizer/venues/{id}/delete', [OrganizerVenueController::class, 'delete'], ['role:organizer', 'csrf'], 'organizer.venues.delete');
    $router->get('/organizer/reviews', [OrganizerReviewController::class, 'index'], ['role:organizer'], 'organizer.reviews.index');
    $router->post('/organizer/reviews/{id}/reply', [OrganizerReviewController::class, 'reply'], ['role:organizer', 'csrf'], 'organizer.reviews.reply');
    $router->get('/admin/dashboard', [DashboardController::class, 'admin'], ['role:super-admin'], 'admin.dashboard');
    $router->get('/admin/events/trash', [AdminEventController::class, 'trash'], ['role:super-admin'], 'admin.events.trash');
    $router->post('/admin/events/trash/{id}/restore', [AdminEventController::class, 'restore'], ['role:super-admin', 'csrf'], 'admin.events.restore');
    $router->get('/admin/blog', [AdminBlogController::class, 'index'], ['role:super-admin'], 'admin.blog.index');
    $router->get('/admin/blog/create', [AdminBlogController::class, 'create'], ['role:super-admin'], 'admin.blog.create');
    $router->post('/admin/blog', [AdminBlogController::class, 'store'], ['role:super-admin', 'csrf'], 'admin.blog.store');
    $router->get('/admin/blog/{id}/edit', [AdminBlogController::class, 'edit'], ['role:super-admin'], 'admin.blog.edit');
    $router->post('/admin/blog/{id}', [AdminBlogController::class, 'update'], ['role:super-admin', 'csrf'], 'admin.blog.update');
    $router->get('/admin/blog/{id}/preview', [AdminBlogController::class, 'preview'], ['role:super-admin'], 'admin.blog.preview');
    $router->post('/admin/blog/{id}/publish', [AdminBlogController::class, 'publish'], ['role:super-admin', 'csrf'], 'admin.blog.publish');
    $router->post('/admin/blog/{id}/unpublish', [AdminBlogController::class, 'unpublish'], ['role:super-admin', 'csrf'], 'admin.blog.unpublish');
    $router->post('/admin/blog/{id}/delete', [AdminBlogController::class, 'delete'], ['role:super-admin', 'csrf'], 'admin.blog.delete');
    $router->get('/admin/analytics', [AdminAnalyticsController::class, 'index'], ['role:super-admin'], 'admin.analytics.index');
    $router->get('/admin/reports', [AdminReportController::class, 'index'], ['role:super-admin'], 'admin.reports.index');
    $router->get('/admin/reports.csv', [AdminReportController::class, 'export'], ['role:super-admin'], 'admin.reports.export');
    $router->get('/admin/reports.pdf', [AdminReportController::class, 'pdf'], ['role:super-admin'], 'admin.reports.pdf');
    $router->get('/admin/reports.xml', [AdminReportController::class, 'spreadsheet'], ['role:super-admin'], 'admin.reports.spreadsheet');
    $router->get('/admin/contact', [AdminContactController::class, 'index'], ['role:super-admin'], 'admin.contact.index');
    $router->get('/admin/contact/{id}', [AdminContactController::class, 'show'], ['role:super-admin'], 'admin.contact.show');
    $router->post('/admin/contact/{id}/status', [AdminContactController::class, 'status'], ['role:super-admin', 'csrf'], 'admin.contact.status');
    $router->post('/admin/contact/{id}/reply', [AdminContactController::class, 'reply'], ['role:super-admin', 'csrf'], 'admin.contact.reply');
    $router->get('/admin/newsletter', [AdminNewsletterController::class, 'index'], ['role:super-admin'], 'admin.newsletter.index');
    $router->get('/admin/newsletter/create', [AdminNewsletterController::class, 'create'], ['role:super-admin'], 'admin.newsletter.create');
    $router->post('/admin/newsletter', [AdminNewsletterController::class, 'store'], ['role:super-admin', 'csrf'], 'admin.newsletter.store');
    $router->post('/admin/newsletter/{id}/queue', [AdminNewsletterController::class, 'queue'], ['role:super-admin', 'csrf'], 'admin.newsletter.queue');
    $router->get('/admin/users', [AdminUserController::class, 'index'], ['role:super-admin'], 'admin.users.index');
    $router->get('/admin/users/{id}', [AdminUserController::class, 'show'], ['role:super-admin'], 'admin.users.show');
    $router->post('/admin/users/{id}/suspend', [AdminUserController::class, 'suspend'], ['role:super-admin', 'csrf'], 'admin.users.suspend');
    $router->post('/admin/users/{id}/deactivate', [AdminUserController::class, 'deactivate'], ['role:super-admin', 'csrf'], 'admin.users.deactivate');
    $router->post('/admin/users/{id}/reactivate', [AdminUserController::class, 'reactivate'], ['role:super-admin', 'csrf'], 'admin.users.reactivate');
    $router->get('/admin/organizers', [AdminOrganizerController::class, 'index'], ['role:super-admin'], 'admin.organizers.index');
    $router->get('/admin/organizers/{id}', [AdminOrganizerController::class, 'show'], ['role:super-admin'], 'admin.organizers.show');
    $router->post('/admin/organizers/{id}/approve', [AdminOrganizerController::class, 'approve'], ['role:super-admin', 'csrf'], 'admin.organizers.approve');
    $router->post('/admin/organizers/{id}/reject', [AdminOrganizerController::class, 'reject'], ['role:super-admin', 'csrf'], 'admin.organizers.reject');
    $router->get('/admin/categories', [AdminCategoryController::class, 'index'], ['role:super-admin'], 'admin.categories.index');
    $router->get('/admin/categories/create', [AdminCategoryController::class, 'create'], ['role:super-admin'], 'admin.categories.create');
    $router->post('/admin/categories', [AdminCategoryController::class, 'store'], ['role:super-admin', 'csrf'], 'admin.categories.store');
    $router->get('/admin/categories/{id}/edit', [AdminCategoryController::class, 'edit'], ['role:super-admin'], 'admin.categories.edit');
    $router->post('/admin/categories/{id}', [AdminCategoryController::class, 'update'], ['role:super-admin', 'csrf'], 'admin.categories.update');
    $router->post('/admin/categories/{id}/status', [AdminCategoryController::class, 'setActive'], ['role:super-admin', 'csrf'], 'admin.categories.status');
    $router->get('/admin/events', [AdminEventController::class, 'index'], ['role:super-admin'], 'admin.events.index');
    $router->get('/admin/events/{id}', [AdminEventController::class, 'show'], ['role:super-admin'], 'admin.events.show');
    $router->post('/admin/events/{id}/approve', [AdminEventController::class, 'approve'], ['role:super-admin', 'csrf'], 'admin.events.approve');
    $router->post('/admin/events/{id}/reject', [AdminEventController::class, 'reject'], ['role:super-admin', 'csrf'], 'admin.events.reject');
    $router->post('/admin/events/{id}/publish', [AdminEventController::class, 'publish'], ['role:super-admin', 'csrf'], 'admin.events.publish');
    $router->post('/admin/events/{id}/complete', [AdminEventController::class, 'complete'], ['role:super-admin', 'csrf'], 'admin.events.complete');
    $router->post('/admin/events/{id}/cancel', [AdminEventController::class, 'cancel'], ['role:super-admin', 'csrf'], 'admin.events.cancel');
    $router->post('/admin/events/{id}/delete', [AdminEventController::class, 'delete'], ['role:super-admin', 'csrf'], 'admin.events.delete');
    $router->get('/admin/reviews', [AdminReviewController::class, 'index'], ['role:super-admin'], 'admin.reviews.index');
    $router->post('/admin/reviews/{id}/publish', [AdminReviewController::class, 'publish'], ['role:super-admin', 'csrf'], 'admin.reviews.publish');
    $router->post('/admin/reviews/{id}/hide', [AdminReviewController::class, 'hide'], ['role:super-admin', 'csrf'], 'admin.reviews.hide');
    $router->get('/admin/payments', [AdminPaymentController::class, 'index'], ['role:super-admin'], 'admin.payments.index');
    $router->get('/admin/payments/{id}', [AdminPaymentController::class, 'show'], ['role:super-admin'], 'admin.payments.show');
    $router->post('/admin/payments/{id}/verify', [AdminPaymentController::class, 'verify'], ['role:super-admin', 'csrf'], 'admin.payments.verify');
    $router->post('/admin/payments/{id}/reject', [AdminPaymentController::class, 'reject'], ['role:super-admin', 'csrf'], 'admin.payments.reject');
    $router->get('/admin/settings', [AdminSettingsController::class, 'edit'], ['role:super-admin'], 'admin.settings.edit');
    $router->post('/admin/settings', [AdminSettingsController::class, 'update'], ['role:super-admin', 'csrf'], 'admin.settings.update');
    $router->get('/admin/operations', [AdminOperationsController::class, 'index'], ['role:super-admin'], 'admin.operations.index');
    $router->post('/admin/operations/maintenance', [AdminOperationsController::class, 'updateMaintenance'], ['role:super-admin', 'csrf'], 'admin.operations.maintenance');
    $router->get('/admin/cms', [AdminCmsController::class, 'index'], ['role:super-admin'], 'admin.cms.index');
    $router->get('/admin/cms/pages/{slug}', [AdminCmsController::class, 'editPage'], ['role:super-admin'], 'admin.cms.pages.edit');
    $router->post('/admin/cms/pages/{slug}', [AdminCmsController::class, 'updatePage'], ['role:super-admin', 'csrf'], 'admin.cms.pages.update');
    $router->post('/admin/cms/pages/{slug}/publish', [AdminCmsController::class, 'publishPage'], ['role:super-admin', 'csrf'], 'admin.cms.pages.publish');
    $router->post('/admin/cms/pages/{slug}/unpublish', [AdminCmsController::class, 'unpublishPage'], ['role:super-admin', 'csrf'], 'admin.cms.pages.unpublish');
    $router->get('/admin/cms/faqs/create', [AdminCmsController::class, 'createFaq'], ['role:super-admin'], 'admin.cms.faqs.create');
    $router->post('/admin/cms/faqs', [AdminCmsController::class, 'storeFaq'], ['role:super-admin', 'csrf'], 'admin.cms.faqs.store');
    $router->get('/admin/cms/faqs/{id}/edit', [AdminCmsController::class, 'editFaq'], ['role:super-admin'], 'admin.cms.faqs.edit');
    $router->post('/admin/cms/faqs/{id}', [AdminCmsController::class, 'updateFaq'], ['role:super-admin', 'csrf'], 'admin.cms.faqs.update');
    $router->post('/admin/cms/faqs/{id}/status', [AdminCmsController::class, 'setFaqActive'], ['role:super-admin', 'csrf'], 'admin.cms.faqs.status');
    $router->get('/admin/cms/banners/create', [AdminCmsController::class, 'createBanner'], ['role:super-admin'], 'admin.cms.banners.create');
    $router->post('/admin/cms/banners', [AdminCmsController::class, 'storeBanner'], ['role:super-admin', 'csrf'], 'admin.cms.banners.store');
    $router->get('/admin/cms/banners/{id}/edit', [AdminCmsController::class, 'editBanner'], ['role:super-admin'], 'admin.cms.banners.edit');
    $router->post('/admin/cms/banners/{id}', [AdminCmsController::class, 'updateBanner'], ['role:super-admin', 'csrf'], 'admin.cms.banners.update');
    $router->post('/admin/cms/banners/{id}/status', [AdminCmsController::class, 'setBannerActive'], ['role:super-admin', 'csrf'], 'admin.cms.banners.status');
    $router->get('/settings/password', [AuthController::class, 'showChangePassword'], ['auth'], 'password.change');
    $router->post('/settings/password', [AuthController::class, 'changePassword'], ['auth', 'csrf'], 'password.change.submit');
};
