<?php

declare(strict_types=1);

use OEMS\App\Controllers\AuthController;
use OEMS\App\Controllers\AdminCategoryController;
use OEMS\App\Controllers\AdminEventController;
use OEMS\App\Controllers\DashboardController;
use OEMS\App\Controllers\HomeController;
use OEMS\App\Controllers\OrganizerEventController;
use OEMS\App\Controllers\OrganizerVenueController;
use OEMS\App\Controllers\ParticipantRegistrationController;
use OEMS\App\Controllers\ParticipantFavoriteController;
use OEMS\App\Controllers\ParticipantTicketController;
use OEMS\App\Controllers\ProfileController;
use OEMS\App\Controllers\PublicEventController;
use OEMS\Core\Router;

return static function (Router $router): void {
    $router->get('/', [HomeController::class, 'index'], name: 'home');
    $router->get('/events', [PublicEventController::class, 'index'], name: 'events.index');
    $router->get('/events/{slug}', [PublicEventController::class, 'show'], name: 'events.show');

    $router->get('/login', [AuthController::class, 'showLogin'], ['guest'], 'login');
    $router->post('/login', [AuthController::class, 'login'], ['guest', 'csrf'], 'login.submit');
    $router->get('/register', [AuthController::class, 'showRegister'], ['guest'], 'register');
    $router->post('/register', [AuthController::class, 'register'], ['guest', 'csrf'], 'register.submit');
    $router->get('/verify-email/{token}', [AuthController::class, 'verifyEmail'], ['guest'], 'verify-email');
    $router->get('/forgot-password', [AuthController::class, 'showForgotPassword'], ['guest'], 'password.request');
    $router->post('/forgot-password', [AuthController::class, 'sendResetLink'], ['guest', 'csrf'], 'password.email');
    $router->get('/reset-password/{token}', [AuthController::class, 'showResetPassword'], ['guest'], 'password.reset');
    $router->post('/reset-password/{token}', [AuthController::class, 'resetPassword'], ['guest', 'csrf'], 'password.update');

    $router->post('/logout', [AuthController::class, 'logout'], ['auth', 'csrf'], 'logout');
    $router->get('/dashboard', [DashboardController::class, 'index'], ['auth'], 'dashboard');
    $router->get('/profile', [ProfileController::class, 'edit'], ['auth'], 'profile.edit');
    $router->post('/profile', [ProfileController::class, 'update'], ['auth', 'csrf'], 'profile.update');
    $router->get('/participant/dashboard', [DashboardController::class, 'participant'], ['role:participant'], 'participant.dashboard');
    $router->get('/participant/favorites', [ParticipantFavoriteController::class, 'index'], ['role:participant'], 'participant.favorites.index');
    $router->post('/participant/favorites/{id}', [ParticipantFavoriteController::class, 'store'], ['role:participant', 'csrf'], 'participant.favorites.store');
    $router->post('/participant/favorites/{id}/remove', [ParticipantFavoriteController::class, 'destroy'], ['role:participant', 'csrf'], 'participant.favorites.destroy');
    $router->get('/participant/events/{slug}/register', [ParticipantRegistrationController::class, 'create'], ['role:participant'], 'participant.registrations.create');
    $router->post('/participant/events/{slug}/register', [ParticipantRegistrationController::class, 'store'], ['role:participant', 'csrf'], 'participant.registrations.store');
    $router->get('/participant/registrations', [ParticipantRegistrationController::class, 'index'], ['role:participant'], 'participant.registrations.index');
    $router->get('/participant/registrations/{id}', [ParticipantRegistrationController::class, 'show'], ['role:participant'], 'participant.registrations.show');
    $router->post('/participant/registrations/{id}/cancel', [ParticipantRegistrationController::class, 'cancel'], ['role:participant', 'csrf'], 'participant.registrations.cancel');
    $router->get('/participant/tickets', [ParticipantTicketController::class, 'index'], ['role:participant'], 'participant.tickets.index');
    $router->get('/participant/tickets/{id}', [ParticipantTicketController::class, 'show'], ['role:participant'], 'participant.tickets.show');
    $router->get('/participant/tickets/{id}/qr', [ParticipantTicketController::class, 'qr'], ['role:participant'], 'participant.tickets.qr');
    $router->get('/participant/tickets/{id}/pdf', [ParticipantTicketController::class, 'pdf'], ['role:participant'], 'participant.tickets.pdf');
    $router->get('/organizer/dashboard', [DashboardController::class, 'organizer'], ['role:organizer'], 'organizer.dashboard');
    $router->get('/organizer/events', [OrganizerEventController::class, 'index'], ['role:organizer'], 'organizer.events.index');
    $router->get('/organizer/events/create', [OrganizerEventController::class, 'create'], ['role:organizer'], 'organizer.events.create');
    $router->post('/organizer/events', [OrganizerEventController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.events.store');
    $router->get('/organizer/events/{id}', [OrganizerEventController::class, 'show'], ['role:organizer'], 'organizer.events.show');
    $router->get('/organizer/events/{id}/edit', [OrganizerEventController::class, 'edit'], ['role:organizer'], 'organizer.events.edit');
    $router->post('/organizer/events/{id}', [OrganizerEventController::class, 'update'], ['role:organizer', 'csrf'], 'organizer.events.update');
    $router->post('/organizer/events/{id}/submit', [OrganizerEventController::class, 'submit'], ['role:organizer', 'csrf'], 'organizer.events.submit');
    $router->post('/organizer/events/{id}/cancel', [OrganizerEventController::class, 'cancel'], ['role:organizer', 'csrf'], 'organizer.events.cancel');
    $router->post('/organizer/events/{id}/delete', [OrganizerEventController::class, 'delete'], ['role:organizer', 'csrf'], 'organizer.events.delete');
    $router->get('/organizer/venues', [OrganizerVenueController::class, 'index'], ['role:organizer'], 'organizer.venues.index');
    $router->get('/organizer/venues/create', [OrganizerVenueController::class, 'create'], ['role:organizer'], 'organizer.venues.create');
    $router->post('/organizer/venues', [OrganizerVenueController::class, 'store'], ['role:organizer', 'csrf'], 'organizer.venues.store');
    $router->get('/organizer/venues/{id}/edit', [OrganizerVenueController::class, 'edit'], ['role:organizer'], 'organizer.venues.edit');
    $router->post('/organizer/venues/{id}', [OrganizerVenueController::class, 'update'], ['role:organizer', 'csrf'], 'organizer.venues.update');
    $router->post('/organizer/venues/{id}/delete', [OrganizerVenueController::class, 'delete'], ['role:organizer', 'csrf'], 'organizer.venues.delete');
    $router->get('/admin/dashboard', [DashboardController::class, 'admin'], ['role:super-admin'], 'admin.dashboard');
    $router->get('/admin/categories', [AdminCategoryController::class, 'index'], ['role:super-admin'], 'admin.categories.index');
    $router->get('/admin/categories/create', [AdminCategoryController::class, 'create'], ['role:super-admin'], 'admin.categories.create');
    $router->post('/admin/categories', [AdminCategoryController::class, 'store'], ['role:super-admin', 'csrf'], 'admin.categories.store');
    $router->get('/admin/categories/{id}/edit', [AdminCategoryController::class, 'edit'], ['role:super-admin'], 'admin.categories.edit');
    $router->post('/admin/categories/{id}', [AdminCategoryController::class, 'update'], ['role:super-admin', 'csrf'], 'admin.categories.update');
    $router->post('/admin/categories/{id}/status', [AdminCategoryController::class, 'setActive'], ['role:super-admin', 'csrf'], 'admin.categories.status');
    $router->get('/admin/events', [AdminEventController::class, 'index'], ['role:super-admin'], 'admin.events.index');
    $router->get('/admin/events/{id}', [AdminEventController::class, 'show'], ['role:super-admin'], 'admin.events.show');
    $router->post('/admin/events/{id}/approve', [AdminEventController::class, 'approve'], ['role:super-admin', 'csrf'], 'admin.events.approve');
    $router->post('/admin/events/{id}/reject', [AdminEventController::class, 'reject'], ['role:super-admin', 'csrf'], 'admin.events.reject');
    $router->post('/admin/events/{id}/publish', [AdminEventController::class, 'publish'], ['role:super-admin', 'csrf'], 'admin.events.publish');
    $router->post('/admin/events/{id}/complete', [AdminEventController::class, 'complete'], ['role:super-admin', 'csrf'], 'admin.events.complete');
    $router->post('/admin/events/{id}/cancel', [AdminEventController::class, 'cancel'], ['role:super-admin', 'csrf'], 'admin.events.cancel');
    $router->get('/settings/password', [AuthController::class, 'showChangePassword'], ['auth'], 'password.change');
    $router->post('/settings/password', [AuthController::class, 'changePassword'], ['auth', 'csrf'], 'password.change.submit');
};
