<div class="dashboard-page-heading organizer-page-heading">
    <div><p class="dashboard-kicker"><i class="ph ph-browser" aria-hidden="true"></i><span>Public content</span></p><h1>Content management</h1><p>Publish fixed information pages, answer common questions, and schedule home banners.</p></div>
    <div class="flex flex-wrap gap-2"><a class="button button--quiet" href="/admin/cms/faqs/create"><i class="ph ph-plus" aria-hidden="true"></i><span>Add FAQ</span></a><a class="button button--primary" href="/admin/cms/banners/create"><i class="ph ph-image" aria-hidden="true"></i><span>Add banner</span></a></div>
</div>

<section class="dashboard-panel mt-8" aria-labelledby="cms-pages">
    <div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-file-text" aria-hidden="true"></i></span><div><h2 id="cms-pages">Information pages</h2><p>Route identities are fixed and cannot be renamed or deleted.</p></div></div>
    <div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Fixed public pages</caption><thead><tr><th scope="col">Page</th><th scope="col">Route</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>
    <?php foreach ($pages as $page): $published = ($page['status'] ?? '') === 'published'; ?><tr><td data-label="Page"><div class="organizer-table__primary organizer-table__value"><strong><?= e($page['title']) ?></strong><small><?= e($page['meta_description'] ?? 'No metadata summary') ?></small></div></td><td class="organizer-table__value" data-label="Route"><code>/<?= e($page['slug']) ?></code></td><td data-label="Status"><span class="status-chip <?= $published ? 'status-chip--published' : 'status-chip--draft' ?>"><?= $published ? 'Published' : 'Draft' ?></span></td><td class="organizer-table__action" data-label="Actions"><div class="admin-table-actions"><a class="button button--quiet button--compact" href="/admin/cms/pages/<?= e($page['slug']) ?>"><i class="ph ph-pencil-simple" aria-hidden="true"></i><span>Edit</span></a><form action="/admin/cms/pages/<?= e($page['slug']) ?>/<?= $published ? 'unpublish' : 'publish' ?>" method="post" data-form-kind="action"<?= $published ? ' data-confirm="Unpublish this page? It will no longer be visible publicly."' : '' ?>><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><button class="button button--compact <?= $published ? 'button--danger' : 'button--quiet' ?>" type="submit" data-submit-label="Updating page…"><span data-submit-text><?= $published ? 'Unpublish' : 'Publish' ?></span></button></form></div></td></tr><?php endforeach; ?>
    </tbody></table></div>
</section>

<section class="dashboard-panel mt-6" aria-labelledby="cms-faqs">
    <div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-question" aria-hidden="true"></i></span><div><h2 id="cms-faqs">Frequently asked questions</h2><p>Only active answers appear on the public FAQ page.</p></div></div>
    <?php if ($faqs === []): ?>
        <div class="empty-state mt-6"><span class="empty-state__icon"><i class="ph ph-question" aria-hidden="true"></i></span><strong>No FAQs yet</strong><p>Add the first public answer.</p><a class="button button--primary" href="/admin/cms/faqs/create">Add FAQ</a></div>
    <?php else: ?>
        <div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Managed FAQs</caption><thead><tr><th scope="col">Question</th><th scope="col">Order</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>
        <?php foreach ($faqs as $faq): $active = !empty($faq['is_active']); ?><tr><td data-label="Question"><div class="organizer-table__primary organizer-table__value"><strong><?= e($faq['question']) ?></strong><small><?= e($faq['category'] ?? 'General') ?></small></div></td><td data-label="Order"><?= e($faq['sort_order']) ?></td><td data-label="Status"><span class="status-chip <?= $active ? 'status-chip--active' : 'status-chip--inactive' ?>"><?= $active ? 'Active' : 'Inactive' ?></span></td><td class="organizer-table__action" data-label="Actions"><div class="admin-table-actions"><a class="button button--quiet button--compact" href="/admin/cms/faqs/<?= e($faq['id']) ?>/edit">Edit</a><form action="/admin/cms/faqs/<?= e($faq['id']) ?>/status" method="post" data-form-kind="action"<?= $active ? ' data-confirm="Deactivate this FAQ? It will disappear from public help."' : '' ?>><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="is_active" value="<?= $active ? '0' : '1' ?>"><button class="button button--compact <?= $active ? 'button--danger' : 'button--quiet' ?>" type="submit" data-submit-label="Updating FAQ…"><span data-submit-text><?= $active ? 'Deactivate' : 'Activate' ?></span></button></form></div></td></tr><?php endforeach; ?>
        </tbody></table></div>
    <?php endif; ?>
</section>

<section class="dashboard-panel mt-6" aria-labelledby="cms-banners">
    <div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-image" aria-hidden="true"></i></span><div><h2 id="cms-banners">Home banners</h2><p>Active banners also respect their optional start and end times.</p></div></div>
    <?php if ($banners === []): ?>
        <div class="empty-state mt-6"><span class="empty-state__icon"><i class="ph ph-image" aria-hidden="true"></i></span><strong>No banners yet</strong><p>Create a scheduled home-page message.</p><a class="button button--primary" href="/admin/cms/banners/create">Add banner</a></div>
    <?php else: ?>
        <div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Managed home banners</caption><thead><tr><th scope="col">Banner</th><th scope="col">Schedule</th><th scope="col">Status</th><th scope="col">Actions</th></tr></thead><tbody>
        <?php foreach ($banners as $banner): $active = !empty($banner['is_active']); ?><tr><td data-label="Banner"><div class="organizer-table__primary organizer-table__value"><strong><?= e($banner['title']) ?></strong><small><?= e($banner['subtitle'] ?? 'No subtitle') ?></small></div></td><td data-label="Schedule"><small><?= e($banner['starts_at'] ?? 'Immediately') ?><br><?= e($banner['ends_at'] ?? 'No end date') ?></small></td><td data-label="Status"><span class="status-chip <?= $active ? 'status-chip--active' : 'status-chip--inactive' ?>"><?= $active ? 'Active' : 'Inactive' ?></span></td><td class="organizer-table__action" data-label="Actions"><div class="admin-table-actions"><a class="button button--quiet button--compact" href="/admin/cms/banners/<?= e($banner['id']) ?>/edit">Edit</a><form action="/admin/cms/banners/<?= e($banner['id']) ?>/status" method="post" data-form-kind="action"<?= $active ? ' data-confirm="Deactivate this banner? It will no longer appear on the home page."' : '' ?>><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><input type="hidden" name="is_active" value="<?= $active ? '0' : '1' ?>"><button class="button button--compact <?= $active ? 'button--danger' : 'button--quiet' ?>" type="submit" data-submit-label="Updating banner…"><span data-submit-text><?= $active ? 'Deactivate' : 'Activate' ?></span></button></form></div></td></tr><?php endforeach; ?>
        </tbody></table></div>
    <?php endif; ?>
</section>
