<?php
$eventStatuses = ['' => 'All lifecycle states', 'draft' => 'Draft', 'pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected', 'published' => 'Published', 'completed' => 'Completed', 'cancelled' => 'Cancelled'];
$lifecycle = (array) ($summary['lifecycle'] ?? []);
$registrations = (array) ($summary['registrations'] ?? []);
$payments = (array) ($summary['verified_payments'] ?? []);
$lifecycleLabels = ['draft' => 'Draft', 'pending' => 'Pending', 'approved' => 'Approved', 'rejected' => 'Rejected', 'published' => 'Published', 'completed' => 'Completed', 'cancelled' => 'Cancelled'];
$registrationLabels = ['pending' => 'Pending', 'confirmed' => 'Confirmed', 'cancelled' => 'Cancelled', 'waitlisted' => 'Waitlisted', 'refunded' => 'Refunded'];
?>
<div class="dashboard-page-heading organizer-page-heading"><div><p class="dashboard-kicker"><i class="ph ph-chart-line-up" aria-hidden="true"></i><span>Platform operations</span></p><h1>Platform analytics</h1><p>Moderation, participation, attendance, and verified settlement signals.</p></div><a class="button button--quiet" href="/admin/reports"><i class="ph ph-files" aria-hidden="true"></i><span>Open reports</span></a></div>

<?php if ($filterError !== null): ?><div class="form-alert mt-6" role="alert"><i class="ph ph-warning-circle" aria-hidden="true"></i><span><?= e($filterError) ?></span></div><?php endif; ?>

<section class="dashboard-panel mt-8" aria-labelledby="admin-analytics-filters"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-funnel" aria-hidden="true"></i></span><div><h2 id="admin-analytics-filters">Analytics filters</h2><p>Choose up to 366 inclusive calendar days and optional event filters.</p></div></div>
<form class="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)_minmax(0,0.8fr)_minmax(0,0.55fr)_auto]" method="get" action="/admin/analytics" data-form-kind="filter">
<label class="form-field" for="admin-analytics-start"><span>Start date</span><input id="admin-analytics-start" name="start" type="date" value="<?= e($range['start'] ?? '') ?>"></label>
<label class="form-field" for="admin-analytics-end"><span>End date</span><input id="admin-analytics-end" name="end" type="date" value="<?= e($range['end'] ?? '') ?>"></label>
<label class="form-field" for="admin-analytics-status"><span>Event status</span><select id="admin-analytics-status" name="event_status"><?php foreach ($eventStatuses as $value => $label): ?><option value="<?= e($value) ?>"<?= ($filters['event_status'] ?? '') === $value ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label>
<label class="form-field" for="admin-analytics-currency"><span>Currency</span><input id="admin-analytics-currency" name="currency" maxlength="3" value="<?= e($filters['currency'] ?? '') ?>" placeholder="BDT" autocapitalize="characters"></label>
<div class="flex items-end gap-2"><button class="button button--primary" type="submit">Apply</button><a class="button button--quiet" href="/admin/analytics">Reset</a></div>
</form></section>

<section class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Platform analytics summary">
<div class="dashboard-panel"><span class="text-sm text-[var(--ink-muted)]">Active users</span><strong class="mt-2 block text-3xl" aria-label="Active users: <?= e((int) ($summary['active_users'] ?? 0)) ?>"><?= e((int) ($summary['active_users'] ?? 0)) ?></strong><small><?= e((int) ($summary['approved_organizers'] ?? 0)) ?> approved organizers</small></div>
<div class="dashboard-panel"><span class="text-sm text-[var(--ink-muted)]">Events in range</span><strong class="mt-2 block text-3xl" aria-label="Events in range: <?= e((int) ($lifecycle['total'] ?? 0)) ?>"><?= e((int) ($lifecycle['total'] ?? 0)) ?></strong><small><?= e((int) ($summary['pending_event_queue'] ?? 0)) ?> awaiting moderation</small></div>
<div class="dashboard-panel"><span class="text-sm text-[var(--ink-muted)]">Confirmed registrations</span><strong class="mt-2 block text-3xl" aria-label="Confirmed registrations: <?= e((int) ($registrations['confirmed'] ?? 0)) ?>"><?= e((int) ($registrations['confirmed'] ?? 0)) ?></strong><small><?= e((int) ($summary['attendance_count'] ?? 0)) ?> checked in</small></div>
<div class="dashboard-panel"><span class="text-sm text-[var(--ink-muted)]">Payment review queue</span><strong class="mt-2 block text-3xl" aria-label="Pending payment queue: <?= e((int) ($summary['pending_payment_queue'] ?? 0)) ?>"><?= e((int) ($summary['pending_payment_queue'] ?? 0)) ?></strong><small><?= e((int) ($summary['refund_attention_count'] ?? 0)) ?> refund attention</small></div>
</section>

<?php require base_path('app/Views/components/analytics-charts.php'); ?>

<div class="mt-6 grid gap-6 xl:grid-cols-2">
<section class="dashboard-panel" aria-labelledby="admin-lifecycle-breakdown"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-flow-arrow" aria-hidden="true"></i></span><div><h2 id="admin-lifecycle-breakdown">Lifecycle breakdown</h2><p>Every event state in the selected range.</p></div></div><dl class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><?php foreach ($lifecycleLabels as $status => $label): ?><div class="rounded-xl border border-[var(--line)] p-3" data-lifecycle-status="<?= e($status) ?>"><dt><span class="status-chip status-chip--<?= e($status) ?>"><?= e($label) ?></span></dt><dd class="mt-1 text-xl font-bold"><?= e((int) ($lifecycle[$status] ?? 0)) ?></dd></div><?php endforeach; ?></dl></section>
<section class="dashboard-panel" aria-labelledby="admin-registration-breakdown"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-users-three" aria-hidden="true"></i></span><div><h2 id="admin-registration-breakdown">Registration breakdown</h2><p>Every registration state recorded in the range.</p></div></div><dl class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><?php foreach ($registrationLabels as $status => $label): ?><div class="rounded-xl border border-[var(--line)] p-3" data-registration-status="<?= e($status) ?>"><dt><span class="status-chip status-chip--<?= e($status) ?>"><?= e($label) ?></span></dt><dd class="mt-1 text-xl font-bold"><?= e((int) ($registrations[$status] ?? 0)) ?></dd></div><?php endforeach; ?></dl></section>
</div>

<section class="dashboard-panel mt-6" aria-labelledby="admin-verified-payments"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-currency-circle-dollar" aria-hidden="true"></i></span><div><h2 id="admin-verified-payments">Verified payment totals</h2><p>Exact paid totals are kept separate by currency.</p></div></div><?php if ($payments === []): ?><div class="empty-state mt-6"><span class="empty-state__icon"><i class="ph ph-receipt" aria-hidden="true"></i></span><strong>No verified payments</strong><p>No paid transactions match these filters.</p></div><?php else: ?><dl class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><?php foreach ($payments as $currency => $amount): ?><div class="rounded-xl border border-[var(--line)] p-4"><dt class="text-sm text-[var(--ink-muted)]"><?= e($currency) ?></dt><dd class="mt-1 text-xl font-bold"><?= e($currency) ?> <?= e($amount) ?></dd></div><?php endforeach; ?></dl><?php endif; ?></section>

<div class="mt-6 grid gap-6 xl:grid-cols-2">
<section class="dashboard-panel" aria-labelledby="top-events"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-calendar-check" aria-hidden="true"></i></span><div><h2 id="top-events">Top events</h2><p>Ranked by registrations in the selected range.</p></div></div><?php if (($summary['top_events'] ?? []) === []): ?><div class="empty-state mt-6"><strong>No event activity</strong><p>No registrations match this range.</p></div><?php else: ?><div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Top events by registrations</caption><thead><tr><th>Event ID</th><th>Lifecycle</th><th>Registrations</th></tr></thead><tbody><?php foreach ($summary['top_events'] as $row): ?><?php $eventStatus = (string) ($row['event_status'] ?? ''); ?><tr><td data-label="Event ID">#<?= e((int) ($row['event_id'] ?? 0)) ?></td><td data-label="Lifecycle"><span class="status-chip status-chip--<?= e($eventStatus) ?>"><?= e($lifecycleLabels[$eventStatus] ?? ucfirst($eventStatus)) ?></span></td><td data-label="Registrations"><?= e((int) ($row['registration_count'] ?? 0)) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<section class="dashboard-panel" aria-labelledby="top-categories"><div class="dashboard-panel__heading"><span class="dashboard-panel__icon"><i class="ph ph-tag" aria-hidden="true"></i></span><div><h2 id="top-categories">Top categories</h2><p>Ranked by registrations in the selected range.</p></div></div><?php if (($summary['top_categories'] ?? []) === []): ?><div class="empty-state mt-6"><strong>No category activity</strong><p>No registrations match this range.</p></div><?php else: ?><div class="organizer-table-wrap mt-6"><table class="operations-table organizer-table"><caption class="sr-only">Top categories by registrations</caption><thead><tr><th>Category</th><th>Registrations</th></tr></thead><tbody><?php foreach ($summary['top_categories'] as $row): ?><tr><td data-label="Category"><strong><?= e($row['category_name'] ?? 'Category') ?></strong><small>#<?= e((int) ($row['category_id'] ?? 0)) ?></small></td><td data-label="Registrations"><?= e((int) ($row['registration_count'] ?? 0)) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
</div>
